### ISSUE TITLE
Broken Download Link

### ISSUE THREAD

**Issue by pastanton** [ggu/LanguageSaver#1]
The link https://gabrieluribe.me/language_saver.html no longer appears to work.

**Comment by ggu** [comment]
Thanks for catching that. I recently switched servers for my site, and have some broken links that I'm working on. I re-uploaded the direct link to https://gabrieluribe.me/LanguageSaver.saver.zip. 

I'm not 100% sure that the screen saver works correctly due to issues I had a few years ago with code-signing screen saver apps on macOS for public use, will retry once macOS Ventura releases.

The most reliable way to use the screen saver is to build it in Xcode locally and having the package signed that way for personal use.

**Comment by ggu** [comment]
Fixed by https://github.com/ggu/LanguageSaver/commit/530d7dc1a98d8ca6276d019ac29ee1be2f0594bc
